//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasBancarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasBancarias()
        {
            this.InformacionVentas = new HashSet<InformacionVentas>();
            this.ComprobantesImagenes = new HashSet<ComprobantesImagenes>();
            this.Ventas_Electrodomesticos_Pagos = new HashSet<Ventas_Electrodomesticos_Pagos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string CBU { get; set; }
        public Nullable<int> CuentaPropia { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<decimal> MontoPagar { get; set; }
        public Nullable<System.DateTime> FechaMontoPagar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacionVentas> InformacionVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobantesImagenes> ComprobantesImagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Pagos> Ventas_Electrodomesticos_Pagos { get; set; }
    }
}
