//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sistema_DavidEntities : DbContext
    {
        public Sistema_DavidEntities()
            : base("name=Sistema_DavidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<EstadosClientes> EstadosClientes { get; set; }
        public virtual DbSet<EstadosUsuarios> EstadosUsuarios { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Zonas> Zonas { get; set; }
        public virtual DbSet<Limites> Limites { get; set; }
        public virtual DbSet<StockUsuarios> StockUsuarios { get; set; }
        public virtual DbSet<ProductosVenta> ProductosVenta { get; set; }
        public virtual DbSet<RecorridosCobranzas> RecorridosCobranzas { get; set; }
        public virtual DbSet<Recorridos> Recorridos { get; set; }
        public virtual DbSet<StocksPendientes> StocksPendientes { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<InformacionClientesAsignados> InformacionClientesAsignados { get; set; }
        public virtual DbSet<InformacionVentas> InformacionVentas { get; set; }
        public virtual DbSet<TipoNegocio> TipoNegocio { get; set; }
        public virtual DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public virtual DbSet<ComprobantesImagenes> ComprobantesImagenes { get; set; }
    }
}
