//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionVentas
    {
        public int Id { get; set; }
        public int IdVenta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Entrega { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<decimal> Restante { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public Nullable<int> whatssap { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<int> idCobrador { get; set; }
        public Nullable<decimal> Deuda { get; set; }
        public Nullable<int> ClienteAusente { get; set; }
        public Nullable<System.DateTime> ProximoCobro { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> IdTipoNegocio { get; set; }
        public string TipoNegocio { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
