//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecorridosCobranzas
    {
        public int Id { get; set; }
        public Nullable<int> IdRecorrido { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Tipo { get; set; }
    
        public virtual Recorridos Recorridos { get; set; }
        public virtual Ventas Ventas { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
