//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockUsuarios
    {
        public int Id { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public int IdCategoria { get; set; }
        public int IdUsuario { get; set; }
        public string Estado { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Productos Productos1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
