//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos_Detalle
    {
        public int Id { get; set; }
        public int IdSueldo { get; set; }
        public byte TipoOrigen { get; set; }
        public Nullable<int> IdTipoNegocio { get; set; }
        public decimal BaseMonto { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal ImporteCalc { get; set; }
        public string Observacion { get; set; }
    
        public virtual TipoNegocio TipoNegocio { get; set; }
    }
}
