//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Concepto { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal Abonado { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string NotaInterna { get; set; }
        public byte Estado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioAlta { get; set; }
        public string RutaComprobante { get; set; }
    
        public virtual Sueldos Sueldos1 { get; set; }
        public virtual Sueldos Sueldos2 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
