//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos_Pagos
    {
        public int Id { get; set; }
        public int IdSueldo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Metodo { get; set; }
        public decimal Importe { get; set; }
        public string Nota { get; set; }
        public string RutaComprobante { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioAlta { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
