//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos_Reglas
    {
        public int Id { get; set; }
        public byte IdTipoRegla { get; set; }
        public Nullable<int> IdTipoNegocio { get; set; }
        public decimal MontoDesde { get; set; }
        public Nullable<decimal> MontoHasta { get; set; }
        public decimal Porcentaje { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
    
        public virtual TipoNegocio TipoNegocio { get; set; }
    }
}
