//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Recorridos = new HashSet<Recorridos>();
            this.StocksPendientes = new HashSet<StocksPendientes>();
            this.StocksPendientes1 = new HashSet<StocksPendientes>();
            this.StockUsuarios = new HashSet<StockUsuarios>();
            this.Sueldos = new HashSet<Sueldos>();
            this.Sueldos1 = new HashSet<Sueldos>();
            this.Sueldos_Pagos = new HashSet<Sueldos_Pagos>();
            this.Ventas_Electrodomesticos = new HashSet<Ventas_Electrodomesticos>();
            this.Ventas_Electrodomesticos1 = new HashSet<Ventas_Electrodomesticos>();
            this.Ventas_Electrodomesticos2 = new HashSet<Ventas_Electrodomesticos>();
            this.Ventas_Electrodomesticos_Cuotas = new HashSet<Ventas_Electrodomesticos_Cuotas>();
            this.Ventas_Electrodomesticos_Cuotas1 = new HashSet<Ventas_Electrodomesticos_Cuotas>();
            this.Ventas_Electrodomesticos_Historial = new HashSet<Ventas_Electrodomesticos_Historial>();
            this.Ventas_Electrodomesticos3 = new HashSet<Ventas_Electrodomesticos>();
            this.Ventas = new HashSet<Ventas>();
            this.Ventas_Electrodomesticos_Pagos = new HashSet<Ventas_Electrodomesticos_Pagos>();
        }
    
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Dni { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> CantVentas { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<System.DateTime> UltimaExportacion { get; set; }
        public string UrlExportacion { get; set; }
        public Nullable<int> ClientesCero { get; set; }
        public Nullable<int> IdTipoNegocio { get; set; }
        public Nullable<int> BloqueoSistema { get; set; }
        public Nullable<int> VistaStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual EstadosUsuarios EstadosUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recorridos> Recorridos { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocksPendientes> StocksPendientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocksPendientes> StocksPendientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockUsuarios> StockUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sueldos> Sueldos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sueldos> Sueldos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sueldos_Pagos> Sueldos_Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos> Ventas_Electrodomesticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos> Ventas_Electrodomesticos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos> Ventas_Electrodomesticos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Cuotas> Ventas_Electrodomesticos_Cuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Cuotas> Ventas_Electrodomesticos_Cuotas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Historial> Ventas_Electrodomesticos_Historial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos> Ventas_Electrodomesticos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Pagos> Ventas_Electrodomesticos_Pagos { get; set; }
    }
}
