//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Electrodomesticos_Cuotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas_Electrodomesticos_Cuotas()
        {
            this.Ventas_Electrodomesticos_Historial = new HashSet<Ventas_Electrodomesticos_Historial>();
            this.Ventas_Electrodomesticos_Pagos_Detalle = new HashSet<Ventas_Electrodomesticos_Pagos_Detalle>();
            this.Ventas_Electrodomesticos_Cuotas_Recargos = new HashSet<Ventas_Electrodomesticos_Cuotas_Recargos>();
        }
    
        public int Id { get; set; }
        public int IdVenta { get; set; }
        public int NumeroCuota { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal MontoOriginal { get; set; }
        public decimal MontoRecargos { get; set; }
        public decimal MontoDescuentos { get; set; }
        public decimal MontoPagado { get; set; }
        public Nullable<decimal> MontoRestante { get; set; }
        public string Estado { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaCobro { get; set; }
        public Nullable<int> CobroPendiente { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Ventas_Electrodomesticos Ventas_Electrodomesticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Historial> Ventas_Electrodomesticos_Historial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Pagos_Detalle> Ventas_Electrodomesticos_Pagos_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Cuotas_Recargos> Ventas_Electrodomesticos_Cuotas_Recargos { get; set; }
    }
}
