//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Electrodomesticos_Detalle
    {
        public int Id { get; set; }
        public int IdVenta { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Ventas_Electrodomesticos Ventas_Electrodomesticos { get; set; }
    }
}
