//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Electrodomesticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas_Electrodomesticos()
        {
            this.Ventas_Electrodomesticos_Detalle = new HashSet<Ventas_Electrodomesticos_Detalle>();
            this.Ventas_Electrodomesticos_Historial = new HashSet<Ventas_Electrodomesticos_Historial>();
            this.Ventas_Electrodomesticos_Pagos = new HashSet<Ventas_Electrodomesticos_Pagos>();
            this.Ventas_Electrodomesticos_Cuotas = new HashSet<Ventas_Electrodomesticos_Cuotas>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal ImporteInteres { get; set; }
        public decimal ImporteRecargos { get; set; }
        public decimal ImporteDescuentos { get; set; }
        public string FormaCuotas { get; set; }
        public Nullable<int> CantidadCuotas { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Turno { get; set; }
        public string FranjaHoraria { get; set; }
        public Nullable<decimal> Entrega { get; set; }
        public Nullable<decimal> Restante { get; set; }
        public Nullable<System.DateTime> P_FechaCobro { get; set; }
        public Nullable<int> Comprobante { get; set; }
        public Nullable<int> Orden { get; set; }
        public string RecargoTipo { get; set; }
        public Nullable<decimal> RecargoValor { get; set; }
        public string DescuentoTipo { get; set; }
        public Nullable<decimal> DescuentoValor { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Detalle> Ventas_Electrodomesticos_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Historial> Ventas_Electrodomesticos_Historial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Pagos> Ventas_Electrodomesticos_Pagos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Cuotas> Ventas_Electrodomesticos_Cuotas { get; set; }
    }
}
