//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Electrodomesticos_Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas_Electrodomesticos_Pagos()
        {
            this.Ventas_Electrodomesticos_Pagos_Detalle = new HashSet<Ventas_Electrodomesticos_Pagos_Detalle>();
        }
    
        public int Id { get; set; }
        public int IdVenta { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string MedioPago { get; set; }
        public decimal ImporteTotal { get; set; }
        public string Observacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> ClienteAusente { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> IdCuentaBancaria { get; set; }
        public string TipoInteres { get; set; }
        public Nullable<int> ActualizoUbicacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Electrodomesticos_Pagos_Detalle> Ventas_Electrodomesticos_Pagos_Detalle { get; set; }
        public virtual Ventas_Electrodomesticos Ventas_Electrodomesticos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual CuentasBancarias CuentasBancarias { get; set; }
    }
}
