//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Electrodomesticos_Historial
    {
        public int Id { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdCuota { get; set; }
        public int UsuarioCambio { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public string Campo { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorNuevo { get; set; }
        public string Observacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Ventas_Electrodomesticos Ventas_Electrodomesticos { get; set; }
        public virtual Ventas_Electrodomesticos_Cuotas Ventas_Electrodomesticos_Cuotas { get; set; }
    }
}
