//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Electrodomesticos_Pagos_Detalle
    {
        public int Id { get; set; }
        public int IdPago { get; set; }
        public int IdCuota { get; set; }
        public decimal ImporteAplicado { get; set; }
    
        public virtual Ventas_Electrodomesticos_Pagos Ventas_Electrodomesticos_Pagos { get; set; }
        public virtual Ventas_Electrodomesticos_Cuotas Ventas_Electrodomesticos_Cuotas { get; set; }
    }
}
