//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_David.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.ProductosVenta = new HashSet<ProductosVenta>();
            this.RecorridosCobranzas = new HashSet<RecorridosCobranzas>();
            this.InformacionVentas = new HashSet<InformacionVentas>();
        }
    
        public int Id { get; set; }
        public int idCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Entrega { get; set; }
        public Nullable<decimal> Restante { get; set; }
        public Nullable<System.DateTime> FechaCobro { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public int idVendedor { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Importante { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<int> idCobrador { get; set; }
        public Nullable<System.DateTime> P_FechaCobro { get; set; }
        public Nullable<decimal> P_ValorCuota { get; set; }
        public Nullable<int> Comprobante { get; set; }
        public string Estado { get; set; }
        public string Turno { get; set; }
        public string FranjaHoraria { get; set; }
        public string EstadoCobro { get; set; }
        public Nullable<int> IdTipoNegocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosVenta> ProductosVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecorridosCobranzas> RecorridosCobranzas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacionVentas> InformacionVentas { get; set; }
    }
}
